import { Injectable } from '@angular/core';
import { User } from '../interfaces/user.interface';
import { Auth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, UserCredential } from '@angular/fire/auth';
import { Router } from '@angular/router';
import { BehaviorSubject, Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class AuthService {
  public user: User = {
    email: '',
  };
  private userSubject: BehaviorSubject<User | null> = new BehaviorSubject<User | null>(null);
  user$: Observable<User | null> = this.userSubject.asObservable();

  constructor(private auth: Auth, private router: Router) {}

  getUser(): User {
    return this.user;
  }

  async register(email: string, password: string): Promise<UserCredential> {
    try {
      const userCredential = await createUserWithEmailAndPassword(this.auth, email, password);
      this.user = { email: userCredential.user?.email || '' };
      this.userSubject.next(this.user);
      return userCredential;
    } catch (error) {
      throw error;
    }
  }

  async login(email: string, password: string): Promise<UserCredential> {
    try {
      const userCredential = await signInWithEmailAndPassword(this.auth, email, password);
      this.user = { email: userCredential.user?.email || '' };
      this.userSubject.next(this.user);
      return userCredential;
    } catch (error) {
      throw error;
    }
  }

  async logout(): Promise<void> {
    try {
      await signOut(this.auth);
      this.user = { email: '' };
      this.userSubject.next(this.user);
      this.router.navigate(['/login']);
    } catch (error) {
      console.error('Error al cerrar sesi√≥n:', error);
      throw error;
    }
  }
}
